// Generated by view binder compiler. Do not edit!
package com.example.attendance_tracker.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.attendance_tracker.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityTeacherDashboardBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnAddClass;

  @NonNull
  public final RecyclerView recyclerTeacherClasses;

  @NonNull
  public final TextView tvTeacherDashboardTitle;

  private ActivityTeacherDashboardBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button btnAddClass, @NonNull RecyclerView recyclerTeacherClasses,
      @NonNull TextView tvTeacherDashboardTitle) {
    this.rootView = rootView;
    this.btnAddClass = btnAddClass;
    this.recyclerTeacherClasses = recyclerTeacherClasses;
    this.tvTeacherDashboardTitle = tvTeacherDashboardTitle;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityTeacherDashboardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityTeacherDashboardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_teacher_dashboard, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityTeacherDashboardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnAddClass;
      Button btnAddClass = ViewBindings.findChildViewById(rootView, id);
      if (btnAddClass == null) {
        break missingId;
      }

      id = R.id.recyclerTeacherClasses;
      RecyclerView recyclerTeacherClasses = ViewBindings.findChildViewById(rootView, id);
      if (recyclerTeacherClasses == null) {
        break missingId;
      }

      id = R.id.tvTeacherDashboardTitle;
      TextView tvTeacherDashboardTitle = ViewBindings.findChildViewById(rootView, id);
      if (tvTeacherDashboardTitle == null) {
        break missingId;
      }

      return new ActivityTeacherDashboardBinding((ConstraintLayout) rootView, btnAddClass,
          recyclerTeacherClasses, tvTeacherDashboardTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
