// Generated by view binder compiler. Do not edit!
package com.example.attendance_tracker.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.attendance_tracker.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAttendanceBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnTakePhoto;

  @NonNull
  public final ImageView imgPreview;

  @NonNull
  public final TextView resultTv;

  @NonNull
  public final TextView tvClassName;

  private ActivityAttendanceBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button btnTakePhoto, @NonNull ImageView imgPreview, @NonNull TextView resultTv,
      @NonNull TextView tvClassName) {
    this.rootView = rootView;
    this.btnTakePhoto = btnTakePhoto;
    this.imgPreview = imgPreview;
    this.resultTv = resultTv;
    this.tvClassName = tvClassName;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAttendanceBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAttendanceBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_attendance, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAttendanceBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnTakePhoto;
      Button btnTakePhoto = ViewBindings.findChildViewById(rootView, id);
      if (btnTakePhoto == null) {
        break missingId;
      }

      id = R.id.imgPreview;
      ImageView imgPreview = ViewBindings.findChildViewById(rootView, id);
      if (imgPreview == null) {
        break missingId;
      }

      id = R.id.resultTv;
      TextView resultTv = ViewBindings.findChildViewById(rootView, id);
      if (resultTv == null) {
        break missingId;
      }

      id = R.id.tvClassName;
      TextView tvClassName = ViewBindings.findChildViewById(rootView, id);
      if (tvClassName == null) {
        break missingId;
      }

      return new ActivityAttendanceBinding((ConstraintLayout) rootView, btnTakePhoto, imgPreview,
          resultTv, tvClassName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
