// Generated by view binder compiler. Do not edit!
package com.example.attendance_tracker.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.attendance_tracker.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityStudentListBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnMarkAllPresent;

  @NonNull
  public final Button btnSaveAttendance;

  @NonNull
  public final RecyclerView recyclerStudents;

  @NonNull
  public final TextView tvClassTitle;

  private ActivityStudentListBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button btnMarkAllPresent, @NonNull Button btnSaveAttendance,
      @NonNull RecyclerView recyclerStudents, @NonNull TextView tvClassTitle) {
    this.rootView = rootView;
    this.btnMarkAllPresent = btnMarkAllPresent;
    this.btnSaveAttendance = btnSaveAttendance;
    this.recyclerStudents = recyclerStudents;
    this.tvClassTitle = tvClassTitle;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityStudentListBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityStudentListBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_student_list, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityStudentListBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnMarkAllPresent;
      Button btnMarkAllPresent = ViewBindings.findChildViewById(rootView, id);
      if (btnMarkAllPresent == null) {
        break missingId;
      }

      id = R.id.btnSaveAttendance;
      Button btnSaveAttendance = ViewBindings.findChildViewById(rootView, id);
      if (btnSaveAttendance == null) {
        break missingId;
      }

      id = R.id.recyclerStudents;
      RecyclerView recyclerStudents = ViewBindings.findChildViewById(rootView, id);
      if (recyclerStudents == null) {
        break missingId;
      }

      id = R.id.tvClassTitle;
      TextView tvClassTitle = ViewBindings.findChildViewById(rootView, id);
      if (tvClassTitle == null) {
        break missingId;
      }

      return new ActivityStudentListBinding((ConstraintLayout) rootView, btnMarkAllPresent,
          btnSaveAttendance, recyclerStudents, tvClassTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
