// Generated by view binder compiler. Do not edit!
package com.example.attendance_tracker.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Switch;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.attendance_tracker.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemStudentAttendanceBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Switch switchAttendance;

  @NonNull
  public final TextView tvStudentName;

  private ItemStudentAttendanceBinding(@NonNull ConstraintLayout rootView,
      @NonNull Switch switchAttendance, @NonNull TextView tvStudentName) {
    this.rootView = rootView;
    this.switchAttendance = switchAttendance;
    this.tvStudentName = tvStudentName;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemStudentAttendanceBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemStudentAttendanceBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_student_attendance, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemStudentAttendanceBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.switchAttendance;
      Switch switchAttendance = ViewBindings.findChildViewById(rootView, id);
      if (switchAttendance == null) {
        break missingId;
      }

      id = R.id.tvStudentName;
      TextView tvStudentName = ViewBindings.findChildViewById(rootView, id);
      if (tvStudentName == null) {
        break missingId;
      }

      return new ItemStudentAttendanceBinding((ConstraintLayout) rootView, switchAttendance,
          tvStudentName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
